FPS = 40

WORLD_WIDTH = 1200
WORLD_HEIGHT = 800

WINDOW_WIDTH = 1200
WINDOW_HEIGHT = 850

INFINITY = 10**18

# radians/seconds
ANGLE_SPEED = 6.28318530718

# Tank
TANK_DEFAULT_SPEED = 50
TANK_DEFAULT_RADIUS = 20
TANK_DEFAULT_WEIGHT = 500
TANK_DEFAULT_ANGLE = 0
TANK_DEFAULT_HEALTH = 500
TANK_DEFAULT_HEALTH_REGENERATION = 0
TANK_DEFAULT_COOLDOWN = 1

# Bonus Mark
BONUS_MARK_DEFAULT_RADIUS = 10
BONUS_MARK_DEFAULT_HEALTH = 100
BONUS_MARK_DEFAULT_WEIGHT = 100
BONUS_MARK_DEFAULT_GIVES_SCORE = 1
BONUS_MARK_DEFAULT_SPEED = 0

# Bullet
BULLET_DEFAULT_SPEED = 200
BULLET_DEFAULT_RADIUS = 5
BULLET_DEFAULT_DAMAGE = 50
