FPS = 40

WORLD_WIDTH = 1500
WORLD_HEIGHT = 950

WINDOW_WIDTH = 1500
WINDOW_HEIGHT = 1000

INFINITY = 10**18

# radians/seconds
ANGLE_SPEED = 6.28318530718

# Tank
TANK_DEFAULT_SPEED = 30
TANK_DEFAULT_RADIUS = 12
TANK_DEFAULT_WEIGHT = 1000
TANK_DEFAULT_ANGLE = 0
TANK_DEFAULT_HEALTH = 1000
TANK_DEFAULT_HEALTH_REGENERATION = 50
TANK_DEFAULT_DAMAGE_ADD = 0
TANK_DEFAULT_BULLET_SPEED_ADD = 0
TANK_DEFAULT_COOLDOWN = 0.5

# Bonus Mark
BONUS_MARK_DEFAULT_RADIUS = 6
BONUS_MARK_DEFAULT_HEALTH = 100
BONUS_MARK_DEFAULT_WEIGHT = 100
BONUS_MARK_DEFAULT_GIVES_SCORE = 1
BONUS_MARK_DEFAULT_SPEED = 0

BONUS_MARK_DEFAULT_COUNT = 35
BONUS_MARK_DEFAULT_PLACE_TRIES = 100

# Bullet
BULLET_DEFAULT_SPEED = 120
BULLET_DEFAULT_RADIUS = 3
BULLET_DEFAULT_DAMAGE = 50

# Upgrades
SCORE_NEED_FOR_UPDATE = 5
UPGRADE_MAX_HEALTH = 100
UPGRADE_HEALTH_REGENERATION = 5
UPGRADE_SPEED = 2
UPGRADE_BULLET_SPEED = 6
UPGRADE_DAMAGE = 10
